### PR TITLE
Fix append undo issue

### LINKED ISSUE #26: Appending text can't be undone
Appending text at the end of the current piece can't be undone.
Logging the actions, both append and insert are called when the text is appended, but when undo is called, none of them are called, only the caret is moved to its correct position.

The undoStack includes the append and then the insert commands. Calling undo only pops the insert command, but since `execSuccess` is false, `insert::undo` is not executed.

### PR DESCRIPTION
**Pull request by eugener**
Closes #26

### CODE REVIEW

File: src/main/java/com/gluonhq/richtext/viewmodel/RichTextAreaViewModel.java [hunk 1]
```diff
@@ -115,9 +115,19 @@ public void clearSelection() {
...
+     */
     void insert( String text ) {
         removeSelection();
-        textBuffer.insert(text, getCaretPosition());
+        int caretPosition =  getCaretPosition();
+        if ( caretPosition >= getTextLength()) {
+            textBuffer.append(text);
+        } else {
+            textBuffer.insert(text, caretPosition);
+        }
```
Comment (jperedadnr) [inline src/main/java/com/gluonhq/richtext/viewmodel/RichTextAreaViewModel.java:130]: I was already wondering if the next line should move caret position the length of the text?

File: src/main/java/com/gluonhq/richtext/model/PieceTable.java [hunk 2]
```diff
@@ -165,15 +165,18 @@ static boolean inRange( int index, int start, int length ) {
...
     AppendCmd(String text) {
         this.text = Objects.requireNonNull(text);
     }
 
     @Override
     protected void doUndo(PieceTable pt) {
-        pt.pieces.remove(newPiece);
-        pt.fire( new TextBuffer.DeleteEvent(pt.getTextLength()-text.length(), text.length() ));
+        if (execSuccess) {
+            pt.pieces.remove(newPiece);
```
Comment (jperedadnr) [inline src/main/java/com/gluonhq/richtext/model/PieceTable.java:177]: I've noticed that after appending and undoing the  change, pt.textLength is not updated (has the value of the appended text). Do we need to call?
```
pt.textLength = pt.getTextLength() - text.length();
```

File: src/main/java/com/gluonhq/richtext/viewmodel/RichTextAreaViewModel.java (hunk 1 above)
Comment (eugener) [reply src/main/java/com/gluonhq/richtext/viewmodel/RichTextAreaViewModel.java:130]: Good call... currently we move the caret to 1 char, for some reason. I think it has to move by `text.length()`.
image

File: src/main/java/com/gluonhq/richtext/model/PieceTable.java (hunk 2 above)
Comment (eugener) [reply src/main/java/com/gluonhq/richtext/model/PieceTable.java:177]: Good catch. Since append command is just removing one piece and not using `insert` or `delete` methods - I missed that. Will take care of this.
Also I think we have to convert textLength to a property in both model and viewModel.

Comment (eugener) [reply src/main/java/com/gluonhq/richtext/model/PieceTable.java:165]: Done

File: src/main/java/com/gluonhq/richtext/viewmodel/RichTextAreaViewModel.java (hunk 1 above)
Comment (eugener) [reply src/main/java/com/gluonhq/richtext/viewmodel/RichTextAreaViewModel.java:132]: Done

**Comment by eugener** [comment]
This fix escalated into a lot of good changes!

File: src/main/java/com/gluonhq/richtext/RichTextAreaSkin.java [hunk 3]
```diff
@@ -97,6 +98,7 @@ protected RichTextAreaSkin(final RichTextArea control) {
         // all listeners have to be removed within dispose method
         control.editableProperty().addListener(this::editableChangeListener);
         editableChangeListener(null); // sets up all related listeners
+        control.textLengthProperty.bind(viewModel.textLengthProperty());
```
Comment (jperedadnr) [inline src/main/java/com/gluonhq/richtext/RichTextAreaSkin.java:101]: Use the method. The field `control.textLengthProperty` should be private? 
Or you are making it package protected so you can bind it from skin?

That can break if we decide to introduce a skin package...

It's probably a better approach to add a listener, that can be disposed as the rest of the listeners.

File: src/main/java/com/gluonhq/richtext/RichTextAreaSkin.java [hunk 4]
```diff
@@ -127,6 +129,14 @@ protected RichTextAreaSkin(final RichTextArea control) {
...
     /// PROPERTIES ///////////////////////////////////////////////////////////////
 
+    // textLengthProperty
+    public final ReadOnlyIntegerProperty textLengthProperty() {
+        return viewModel.textLengthProperty();
+    }
+    public final int getTextLength() {
+        return viewModel.getTextLength();
+    }
+
```
Comment (jperedadnr) [inline src/main/java/com/gluonhq/richtext/RichTextAreaSkin.java:139]: why do we need this public API on a skin?

Comment (eugener) [reply src/main/java/com/gluonhq/richtext/RichTextAreaSkin.java:139]: That was a leftover from previous design - will remove

File: src/main/java/com/gluonhq/richtext/RichTextAreaSkin.java (hunk 3 above)
Comment (eugener) [reply src/main/java/com/gluonhq/richtext/RichTextAreaSkin.java:101]: I think we still have the same issue since control's `textLengthProperty` is readonly, so setter has to be package protected. Is there a better solution?

Comment (jperedadnr) [reply src/main/java/com/gluonhq/richtext/RichTextAreaSkin.java:101]: Yes, you are right, that won't work.

At least with the typical MVC approach, the control has some properties and the skin listens to them, but not the other way around. The skin could be removed after all to use a different implementation, so we shouldn't rely on it to update a control property.

Also the control should have a `textProperty` that the user can set with some initial text, and that should go to the skin, which should update the ModelView with it.

After every update of that text, the `textProperty` should have a face value of the current pieceTable. That would allow the user to serialize the "final" text to a file for instance. As a consequence of changes in this property, the lengthTextProperty in the control should not probably needed at all.

With that textProperty, we still need to find a way to update the control from any change in the textBuffer, but it is not clear to me if with MVVC the control should see the model at all.

Comment (jperedadnr) [reply src/main/java/com/gluonhq/richtext/RichTextAreaSkin.java:101]: Anyway, this is probably for a follow-up. Once you are happy with the changes, lets merge and restart the discussion.

**Review by jperedadnr — APPROVED** [review]
