### PR TITLE
Make Document and Decoration serializables

### LINKED ISSUE #297: Open & Save options
Is their any possibility to have this 2 options :
- Save the document (text & decoration) into an external file.
- Open the external file into the document (text & decoration).

I tried to deserialize the DecorationModel & its subclasses, but I always got exceptions because they're not serializable.
So, I which if a method exists to facilitate the operation of saving & opening.

### PR DESCRIPTION
**Pull request by jperedadnr**
Fixes #297

### CODE REVIEW

File: rta/src/main/java/com/gluonhq/richtextarea/RichListCell.java [hunk 1]
```diff
@@ -353,4 +359,11 @@ private Optional<ParagraphTile> getParagraphTile() {
         return Optional.empty();
     }
 
+    private static Color parseColorOrDefault(String color, Color defaultColor) {
+        try {
+            return Color.web(color);
+        } catch (Exception e) {
+            return defaultColor;
```
Comment (johanvos) [inline rta/src/main/java/com/gluonhq/richtextarea/RichListCell.java:366]: Shouldn't a log entry explain here what was being parsed? I can imagine users wondering why they select RED and are returned with the defaultColor.

**Comment by johanvos** [comment]
Looks good, 1 remark.
Apart from that, this is good to go but we should do a release first, and bump the version before we merge this.

File: rta/src/main/java/com/gluonhq/richtextarea/RichListCell.java (hunk 1 above)
Comment (jperedadnr) [reply rta/src/main/java/com/gluonhq/richtextarea/RichListCell.java:366]: `Color::web` admits different formats for colours, like `"#ff0000"` or `"0xff0000"` or `red` or `rgb(255,0,0)`, (see https://github.com/openjdk/jfx/blob/master/modules/javafx.graphics/src/main/java/javafx/scene/paint/Color.java#L288).

But if there are typos or not valid strings, like unknown colours, there would be an IllegalArgumentException exception, and that would be avoided by using a default colour.
